### ISSUE TITLE
Do you have any plans to release the pretrained model ?

### ISSUE THREAD

**Issue by tuner007** [jaywalnut310/linear-transformer-for-table-recognition#1]
Hello,
Thanks so much for sharing your interesting work and training instructions.
Can we download the pre-trained model ?
Thanks in advance

**Comment by jaywalnut310** [comment]
Hi @tuner007, thanks for your interest! I haven't thought before, but if providing the pre-trained model could help your or other's research, it would be an honor of me. I'll provide the pre-trained model soon and let you know then :)

**Comment by tuner007** [comment]
> Hi @tuner007, thanks for your interest! I haven't thought before, but if providing the pre-trained model could help your or other's research, it would be an honor of me. I'll provide the pre-trained model soon and let you know then :)

Thanks for the prompt response. That will be helpful :) 

Thanks !!
